language: cpp
addons:
  apt:
    packages:
      - python3.5
      - python3.5-dev
matrix:
  include:
    - compiler: clang++
      env:
        - MATRIX_EVAL="CC=clang-5 && CXX=clang++-5"
    - compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - python3.5
            - python3.5-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3.5 get-pip.py --user
script:
  - python3.5 -m pip install --user -e .
deploy:
  provider: pypi
  user: "${PYPI_USERNAME}"
  password: "${PYPI_PASSWORD}"
  on:
    tags: true
