language: cpp
addons:
  apt:
    packages:
      - python3.5
      - python3.5-dev
matrix:
  include:
    - compiler: clang++
      env:
        - CXX=clang++
    - compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - python3.5
            - python3.5-dev
      env:
        - CXX=g++5
install:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3 get-pip.py --user
script:
  - pip3 install -e .
deploy:
  provider: pypi
  user: "${PYPI_USERNAME}"
  password: "${PYPI_PASSWORD}"
  on:
    tags: true
