language: cpp
addons:
  apt:
    packages:
      - python3.5
      - python3.5-pip
      - python3.5-dev
script:
  - pip install -e .
deploy:
  provider: pypi
  user: "${PYPI_USERNAME}"
  password: "${PYPI_PASSWORD}"
  on:
    tags: true
