language: cpp
addons:
  apt:
    packages:
      - python3.5
      - python3.5-pip
      - python3.5-dev
matrix:
  include:
    - compiler: clang++
      env:
        - CXX=clang++
    - compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CXX=g++5
script:
  - pip install -e .
deploy:
  provider: pypi
  user: "${PYPI_USERNAME}"
  password: "${PYPI_PASSWORD}"
  on:
    tags: true
