language: cpp
addons:
  apt:
    packages:
      - python3.5
      - python3.5-dev
compiler: g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - python3.5
      - python3.5-dev
before_install:
  - eval "CC=gcc-5 && CXX=g++-5"
install:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3.5 get-pip.py --user
script:
  - python3.5 -m pip install --user -e .
deploy:
  provider: pypi
  user: "${PYPI_USERNAME}"
  password: "${PYPI_PASSWORD}"
  on:
    tags: true
